export const CONFIG = {
  STARTING_CREDITS: 500,
  WEEKLY_CREDIT_POOL: 1000,

  DENOUNCE_ACCUSER_REWARD: 100,
  DENOUNCE_ACCUSER_PENALTY: 50,
  DENOUNCE_TWO_PERSON_ABUSE_THRESHOLD: 3,
  DENOUNCE_TWO_PERSON_ABUSE_PENALTY: 150,
  DENOUNCE_TWO_PERSON_WINDOW_DAYS: 60,
  DENOUNCE_RESPONSE_WINDOW_HOURS: 24,
  DENOUNCE_EXPLANATION_MAX_WORDS: 300,

  AUTO_ASSIGN_HOUR: 14,  // Sunday, collective timezone — when weekly auto-assignment runs

  COLLECTIVE_CODE_LENGTH: 5,
  COLLECTIVE_NAME_MAX_CHARS: 30,

  DEFAULT_TASK_DUE_DAY: 0,
  DEFAULT_TASK_DUE_HOUR: 23,
  DEFAULT_TASK_DUE_MINUTE: 59,
} as const;
